### ISSUE TITLE
Issue with delay between HTTP Get and response more than ~26 second

### ISSUE THREAD

**Issue by surfinlemex** [submariner-io/submariner#2364]
In ours two cluster deployment we can observer several same submariner connections. 
All of the is Active and digagnoses wasn't detect any issues. 
However we have issue with TCP session delay for connections between two POD in diferent clusters.
Can you please let's us know if it's correct configuration when we can see more than one connection as it shown on screenshot in attachment?

Can we somehow delete extra connections?

![image](https://user-images.githubusercontent.com/31878095/228433738-6d188492-6f83-4fdf-a9c9-fe944101b125.png)

**Comment by skitt** [comment]
These are all the same connection (same gateway, same cluster, same remote IP etc.) — I’m guessing you have multiple contexts defined in your kubeconfig; `subctl show connections` tries all available contexts to show the connections.

**Comment by surfinlemex** [comment]
Yes, you're right, the number of connections is equivalent to the number of contexts.
In turn i would like to ask if the same connections can affect on tcp session packets delay.
We have issue with ~26 delay between HTTP get and responce, when we are working via submariner.
Also we have DUP and Out-of-Order packets in that session.


![image](https://user-images.githubusercontent.com/31878095/228480851-2905b46d-6777-40a2-8a7b-bf272289c2e0.png)

**Comment by skitt** [comment]
There is only one connection, you’re seeing it reported multiple times through the different contexts.

Since your traffic goes through this connection (an IPsec tunnel), there can be an impact on the transmission, although since your average RTT is very low (0.5ms) I wouldn’t expect it to be noticeable. I also wouldn’t expect packets to be delivered out-of-order or duplicated, since the IPsec protocol goes to great lengths to avoid that. Perhaps there’s something going wrong between the nodes and the gateway; @sridhargaddam, @aswinsuryan, what do you think?

**Comment by surfinlemex** [comment]
There is a video how our issue is looks like. See attachment.
We have captured traffic in pcap files from both cluster side pods.
I can provide them if needed 

https://user-images.githubusercontent.com/31878095/228494424-509acb72-b3fd-4979-a8a4-efbc3986a0f2.mp4

**Comment by surfinlemex** [comment]
Can you please have a look to the captured traffic from both side?
There is an issue with delay between 3 way handshake and HTTP GET request around 26 second
At the same time ICMP traffic working fine without any retransmission and packets lost, only TCP traffic affected.

![image](https://user-images.githubusercontent.com/31878095/229050488-5205822a-29eb-4a1e-af3b-94cc8e90b169.png)
![image](https://user-images.githubusercontent.com/31878095/229050578-ccecba4b-3b58-48ac-a66b-21c8dee092ef.png)

**Comment by sridhargaddam** [comment]
This is weird. Can you share the following details?

**Environment**: 
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:

Also, the CNI that you are using in your setup.

Note: While running the above commands, you can pass the admin context, otherwise the same information is captured with ALL the contexts. For example: `subctl show all --context ...`

**Comment by surfinlemex** [comment]
You can find requested information it the test file in attachment.
About SNI it's network plugin ("OpenShiftSDN")

We use hardware for our OpenShift deployment. It's shown on diagram
![Diagram](https://user-images.githubusercontent.com/31878095/229074603-5ebbd966-f0e0-4eb7-948e-ae07d916b42c.JPG)

[amsoce02dr-is01.txt](https://github.com/submariner-io/submariner/files/11120053/amsoce02dr-is01.txt)
[amsoce02dr-is01-gather.txt](https://github.com/submariner-io/submariner/files/11120055/amsoce02dr-is01-gather.txt)
[ams-oce2-ocp-is01.txt](https://github.com/submariner-io/submariner/files/11120056/ams-oce2-ocp-is01.txt)
[ams-oce2-ocp-is01-gather.txt](https://github.com/submariner-io/submariner/files/11120058/ams-oce2-ocp-is01-gather.txt)

**Comment by sridhargaddam** [comment]
Thank you for sharing the details. The output of "subctl diagnose all" does not show any errors or warnings.
So, we have to look at other places. In order to understand if there are any errors in various Submariner pods, we would need the logs from the pods which are stored in a directory displayed in the last line of the "subctl gather ..." output.

For example:
```
<SNIP>
...
...
 ✓ Found 0 deployments by label selector "app=submariner-networkplugin-syncer" in namespace "submariner-operator"
 ✓ Found 1 deployments by label selector "app=submariner-lighthouse-agent" in namespace "submariner-operator"
 ✓ Found 1 deployments by label selector "app=submariner-lighthouse-coredns" in namespace "submariner-operator"
Files are stored under directory "submariner-20230331084001/oce02dr"
```

For each cluster, please tar one of the directory contents of the folders shown in the output of "subctl gather" and attach them to this issue. 

Also, may i know the OpenShift version you are using in your setup?

**Comment by yboaron** [comment]
+1 to what @sridhargaddam suggested.

In addition, from the pcap files attached above,  it seems that  TCP MSS values are asymmetric (1410 and 1160) , I would also recommend making sure that you are not running into any MTU related issue. for this you can run subctl verify with small packet size (check [1]),   this option is available in latest subctl version.



[1] 
 subctl verify --context cluster1  --tocontext cluster2 --only connectivity --packet-size 500

**Comment by surfinlemex** [comment]
Looks like we have issue with subctl veryfy connectivity test.. 
Please have a look to the screenshot below
![image](https://user-images.githubusercontent.com/31878095/229692830-cc7c5eb3-d32d-4a42-9784-eb8ec5538657.png)

**Comment by sridhargaddam** [comment]
Following is the command you executed.
```
subctl verify --context admin --tocontext admin --only connectivity
```

As you can see, the context names are the same, hence you are getting the error. Please rename the context of the second cluster from admin to some other name and then re-run the command. 

Following is the sample output of contexts from a KIND setup.

```
[sgaddam@localhost submariner]$ export KUBECONFIG=output/kubeconfigs/kind-config-cluster1:output/kubeconfigs/kind-config-cluster2
[sgaddam@localhost submariner]$ kubectl config get-contexts
CURRENT   NAME       CLUSTER    AUTHINFO   NAMESPACE
*         cluster1   cluster1   cluster1   
          cluster2   cluster2   cluster2 
```

**Comment by surfinlemex** [comment]
Please have a look to the screenshot
![image](https://user-images.githubusercontent.com/31878095/229711137-8775061b-3159-4e2a-a338-66c3e40ce377.png)

**Comment by surfinlemex** [comment]
Please let me know if that test was informative for you?
Can we interrrupt it now?
![image](https://user-images.githubusercontent.com/31878095/229714738-de3bfe4e-7aeb-45a4-82ed-1e155f2c45cf.png)

**Comment by surfinlemex** [comment]
This is proper connectivity test between two contexts in deferent cluster 
[verify connection.txt](https://github.com/submariner-io/submariner/files/11146796/verify.connection.txt)

**Comment by surfinlemex** [comment]
@sridhargaddam  do you have chanse to see the logs file with connection test?

**Comment by surfinlemex** [comment]
@sridhargaddam Please let me know if we can aggange call to troubleshoot our issue with submariner online ?

**Comment by sridhargaddam** [comment]
> This is proper connectivity test between two contexts in deferent cluster [verify connection.txt](https://github.com/submariner-io/submariner/files/11146796/verify.connection.txt)

From the attached logs, I can see 5 failures. 
```
Summarizing 5 Failures:

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote pod when the pod is not on a gateway and the remote pod is not on a gateway [It] should have sent the expected data from the pod to the other pod
github.com/submariner-io/shipyard@v0.14.2/test/e2e/framework/network_pods.go:187

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote service when the pod is not on a gateway and the remote service is not on a gateway [It] should have sent the expected data from the pod to the other pod
github.com/submariner-io/shipyard@v0.14.2/test/e2e/framework/network_pods.go:187

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote service when the pod is not on a gateway and the remote service is on a gateway [It] should have sent the expected data from the pod to the other pod
github.com/submariner-io/shipyard@v0.14.2/test/e2e/framework/network_pods.go:187

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod with HostNetworking connects via TCP to a remote pod when the pod is not on a gateway and the remote pod is not on a gateway [It] should have sent the expected data from the pod to the other pod
github.com/submariner-io/shipyard@v0.14.2/test/e2e/framework/network_pods.go:188

[Fail] [dataplane] Basic TCP connectivity tests across clusters without discovery when a pod connects via TCP to a remote pod in reverse direction when the pod is not on a gateway and the remote pod is not on a gateway [It] should have sent the expected data from the pod to the other pod
github.com/submariner-io/shipyard@v0.14.2/test/e2e/tcp/connectivity.go:69
```

Gateway to Gateway connectivity is working fine and all the failures are when the pod is scheduled on the `non-Gateway` node. So, I suspect that there is some MTU issue which is creating problems for TCP traffic. As @yboaron suggested, lets try with a lower packet-size.

Note: The `--packet-size` option for `subctl verify ....` is only available in the `devel` as its added as part of the current Submariner release (0.15.0). Just for testing, we can use `0.15.0-rc0` image.

```
curl -Ls https://get.submariner.io | VERSION=0.15.0-rc0 bash
export PATH=$PATH:~/.local/bin
echo export PATH=\$PATH:~/.local/bin >> ~/.profile

subctl verify --context oce02dr-gg/api-oce02dr-okd:6443/system:admin  --tocontext amsoce02-gg/api-amsoce02-okd:6443/system:admin --only connectivity --packet-size 500
```

If the output of the above command is success and all the tests PASS, then it implies that there is indeed an MTU issue.

**Comment by surfinlemex** [comment]
Looks like we don't have flag --packet-size
![image](https://user-images.githubusercontent.com/31878095/231106027-51d6c198-3135-46b3-9bb3-2d7cdbf8bb2c.png)
Is there another option to test it?

**Comment by sridhargaddam** [comment]
Looks like you are not using the right version of subctl. Please follow the instructions I shared above on how to download the subctl version 0.15.0-rc0 and use the same version to run the verify command.

**Comment by surfinlemex** [comment]
With new subctl connectivity test all successful.
I did it with different packet size. See screenshots 
![image](https://user-images.githubusercontent.com/31878095/231130159-659446d9-a35a-4ccb-8c4f-390083caf724.png)
![image](https://user-images.githubusercontent.com/31878095/231133529-896bf91c-aa61-4237-b6d4-a5ebb1e197ec.png)

**Comment by sridhargaddam** [comment]
Okay, so its indeed an MTU issue. It looks like the underlay network connecting the clusters are adding some protocol overhead and the default MTU configured on the interfaces is not sufficient. 

Using standard tools, please check the proper MTU between a non-Gateway node to a remote cluster non-Gateway node and once you derive the value, you can force the MTU as shown below.

Add the following annotation on the Gateway nodes of both the clusters.
e.g. kubectl annotate node <node_name> submariner.io/tcp-clamp-mss=<value> 

After adding the annotation, restart the submariner-routeagent pods.
```
kubectl delete pod -n submariner-operator -l app=submariner-routeagent
```

This should fix the latency issue you are seeing with TCP packets.

**Comment by surfinlemex** [comment]
@sridhargaddam I suppose issue Gateway nodes or libreswan. Please have a look to the traceroute screenshots
![image](https://user-images.githubusercontent.com/31878095/231637262-613fd313-3eca-47fb-bfc8-f46c39349a62.png)
![image](https://user-images.githubusercontent.com/31878095/231637346-afeafb97-5940-4c26-b686-c51780d39fb1.png)

**Comment by surfinlemex** [comment]
non-Gateway node MTU 
![image](https://user-images.githubusercontent.com/31878095/231638622-c17edec9-9c25-4602-a1bb-f39952023925.png)

Gateway node MTU
![image](https://user-images.githubusercontent.com/31878095/231638732-cf218e11-d191-454e-8a5d-a8819c74fc1d.png)

non-Gateway node DR cluster
![image](https://user-images.githubusercontent.com/31878095/231639131-8bb0a1ab-bb8a-48ce-9d5e-277372e07d68.png)

Gateway node DR cluster
![image](https://user-images.githubusercontent.com/31878095/231639300-e00bc7a5-bd7a-40f2-ba22-e337f8ad3cf6.png)

Both cluster connected to the same L3 switch and MTU on all switchport is 9032

**Comment by surfinlemex** [comment]
Routing table on Gateway node
![image](https://user-images.githubusercontent.com/31878095/231652282-c347921b-fa01-47fc-acaf-816be4a733a1.png)

Routing table on DR cluster Gateway node
![image](https://user-images.githubusercontent.com/31878095/231652397-5e6db5d5-3183-4d4f-b5e4-79df5bd95ad1.png)

**Comment by surfinlemex** [comment]
I just redeploy all routeragents from both clusters, however issue wasn't resolved 
![image](https://user-images.githubusercontent.com/31878095/231669706-f09352ef-8f4a-462d-aed6-68d3b90abb06.png)

**Comment by surfinlemex** [comment]
This is MTU size test with fragmentation deny between Gateway nodes in different clusters
![image](https://user-images.githubusercontent.com/31878095/231686150-30ae7b9f-6998-40b2-88a0-faa780683aac.png)

**Comment by yboaron** [comment]
@surfinlemex Did you annotate the GW nodes on both clusters with the desired TCP_MSS value as Sridhar mentioned? 

 you should apply  

**kubectl annotate node <gw_node_name> submariner.io/tcp-clamp-mss=1200**

On GWs in both clusters.

and then restart all route_agent pods by running:
 **kubectl delete pod -n submariner-operator -l app=submariner-routeagent**

If the above steps didn't help please attach the latest Submariner logs (**subctl gather** )

**Comment by sridhargaddam** [comment]
> you should apply
> 
> **kubectl annotate node <gw_node_name> submariner.io/tcp-clamp-mss=1200**

From the screenshots that were shared above, it looks like the MTU is 8972. So, instead of 1200, you can use 8972 in the above command.

**Comment by surfinlemex** [comment]
I did it for 1200 before but now owerwritte tcp-clamp-mss by 8900
![image](https://user-images.githubusercontent.com/31878095/231737301-dd1533c7-8940-43e3-b920-c0e575c91984.png)
![image](https://user-images.githubusercontent.com/31878095/231737373-69a74b53-f9a2-4859-8fc9-06b3549e6d74.png)

**Comment by surfinlemex** [comment]
Issue still persist 
![image](https://user-images.githubusercontent.com/31878095/231738114-425935d7-b7b0-4205-8200-dfd823148d10.png)
![image](https://user-images.githubusercontent.com/31878095/231738193-2cf77cb6-7abb-4d33-9baf-a9a65ce83517.png)

**Comment by sridhargaddam** [comment]
> I did it for 1200 before but now owerwritte tcp-clamp-mss by 8900

Did you notice the ~26 secs latency issue even when the MTU was configured with 1200? 
Also, can you check if `ams-oce02-ops01` and `oce02dr-ops01` are the Gateway nodes.

**Comment by surfinlemex** [comment]
We have delay between HTTP Get an Responce all the time... even time for delay almost constant 26  - 27 seconds.
I susspect we have issue with Gateway Node **ams-oce02-ops01**. Can we somehow transfer **submariner-gateway-nz2rh** pod to another node?

Please have a look to info about Gateway nodes:
![image](https://user-images.githubusercontent.com/31878095/231763617-e3b509e6-32db-4928-a8bf-c7fb661d2378.png)
![image](https://user-images.githubusercontent.com/31878095/231763832-5782bcf0-678b-41b5-9a25-9ba7f88ef24a.png)

**Comment by sridhargaddam** [comment]
> I susspect we have issue with Gateway Node **ams-oce02-ops01**. Can we somehow transfer **submariner-gateway-nz2rh** pod to another node?

From your earlier replies, I see that you are using some kind of BareMetal/OnPrem env'. If your cluster nodes are directly reachable over their privateIPs, then there is no need for any public-ip on the Gateway nodes. If you env' meets this requirement, then you can simply remove the `submariner.io/gateway=true` label from the problematic gateway node (i.e., ams-oce02-ops01) and add the `submariner.io/gateway=true` label to some other node. 

The submariner-gateway DaemonSet controller will schedule a submariner-gateway pod on the new node and connections should be established using the new node. For more details on how Submariner Gateway works, you can read the following https://submariner.io/getting-started/architecture/gateway-engine/

**Comment by surfinlemex** [comment]
I just move gateway to ams-oce02-ops3 node. However traceroute still tryin reach DR cluster via former gateway node.
![image](https://user-images.githubusercontent.com/31878095/231957003-bea38207-8aca-4719-b5d6-30990031957a.png)

Please have a look to the traceroute test:
![image](https://user-images.githubusercontent.com/31878095/231959739-9921ea5b-2ad6-41b6-b7da-12a5dd63f7f4.png)

Right now the POD with traceroute hosted on the same node (gateway node ams-oce02-ops03 ).

**Comment by surfinlemex** [comment]
Looks like we lost connectivity with DR cluster after we move gateway on ams-oce02-ops03 node.
![image](https://user-images.githubusercontent.com/31878095/231961906-788748bb-7d85-4f3f-80e2-92fe96b17114.png)

**Comment by surfinlemex** [comment]
Probably it's related to this routes
![image](https://user-images.githubusercontent.com/31878095/231975499-f302cfa4-de52-44d1-9cd3-cf62ebca7534.png)

**Comment by surfinlemex** [comment]
When I delete those routes, tracesoute test looks like this 
![image](https://user-images.githubusercontent.com/31878095/231976697-8454e029-c63f-40d7-a0dc-52d76ec1f620.png)

Gateway node routing table 
![image](https://user-images.githubusercontent.com/31878095/231976872-51136473-0346-4c89-a535-546f6ccc59de.png)

**Comment by surfinlemex** [comment]
This is routing table from previous Gateway node... As I can see the routes 10.136.0.0/14 and 172.29.0.0/16 missing there..
![image](https://user-images.githubusercontent.com/31878095/232009063-6b41ce67-e85a-47c5-9b32-64ca57721347.png)

**Comment by yboaron** [comment]
@surfinlemex , Is the new gateway pod in running state (from the pic you attached, it seems to be in   CrashLoopBackOff) ?

**Comment by surfinlemex** [comment]
@yboaron  Can you please let me know what this error in the logs about?
![image](https://user-images.githubusercontent.com/31878095/232355987-2d5d5844-2544-45c3-b542-43cd1f7b1ea8.png)

**Comment by surfinlemex** [comment]
Please ignore previous message... that was DNS issue
![image](https://user-images.githubusercontent.com/31878095/232451601-89dbf0dc-7225-4d9f-90aa-4e37c4d1fa9c.png)

**Comment by yboaron** [comment]
@surfinlemex What's the status after moving the gw pod to another node?

If you still experiencing the delayed HTTP issue, maybe it will be better to discuss it on [submariner slack channel](https://submariner.io/community/getting-help/#slack)

**Comment by surfinlemex** [comment]
@yboaron can you please provide me your email? I'll invite you in our corporative Slack channel?

**Comment by surfinlemex** [comment]
@yboaron I just sent you invitation for our slack channel

**Comment by surfinlemex** [comment]
There is an additional connectivity test with different timeout and connection attempts.
![image](https://user-images.githubusercontent.com/31878095/232829711-facbfd51-d9ea-47b4-b1c2-2a662077a010.png)

**Comment by yboaron** [comment]
It looks like all Submariner e2e tests are green even when you limit the connection timeout to 30 seconds.

**Comment by surfinlemex** [comment]
I just execute following connecitity tests with trafic captuiring:
![image](https://user-images.githubusercontent.com/31878095/234855925-bd6bb7c0-9843-46a3-8e58-25ea029c28b3.png)

All GW nodes have **ops03** in the name non-gw nodes **ops02** or **ops05**
[submariner.zip](https://github.com/submariner-io/submariner/files/11343329/submariner.zip)

Traffic was captured on four interfaces each node in chain: **vx-submariner**, **tun0**, **vxlan_sys_4789** and physical interface  **eno1np0**

**Comment by yboaron** [comment]
Thanks for uploading the pcap files @surfinlemex , I'll try to check them in the next few days

**Comment by yboaron** [comment]
Could you please add [1] iptables rules on non-gw and gw nodes  on both clusters and rerun the curl test ? 

You can use the following steps to install iptables rules on node: 
A. Find submariner-routeagent-xxxxx pod that runs on the relevant node , you can use [2] for that 
B. Exec into submariner-routeagent pod , see [3] 
C. Apply iptables rules


[1] 

iptables -t raw -I OUTPUT -s <pod cidr from cluster1> -d  <pod cidr from cluster2> -j NOTRACK
iptables -t raw -I OUTPUT -s <pod cidr from cluster2> -d  <pod cidr from cluster1> -j NOTRACK
iptables -t raw -I PREROUTING -s <pod cidr from cluster1> -d  <pod cidr from cluster2> -j NOTRACK
iptables -t raw -I PREROUTING -s <pod cidr from cluster2> -d  <pod cidr from cluster1> -j NOTRACK

[2] 

$ kubectl get pods  -n submariner-operator  -o wide 
NAME                                             READY   STATUS    RESTARTS   AGE    IP           NODE                     NOMINATED NODE   READINESS GATES
submariner-gateway-c7qm2                         1/1     Running   0          7d1h   172.23.0.6   cluster2-worker          <none>           <none>
submariner-globalnet-sljvr                       1/1     Running   0          7d1h   172.23.0.6   cluster2-worker          <none>           <none>
submariner-lighthouse-agent-55655c9b6-7nqc7      1/1     Running   0          7d1h   10.129.1.5   cluster2-worker          <none>           <none>
submariner-lighthouse-coredns-749b7cf9c4-7jx2r   1/1     Running   0          7d1h   10.129.1.6   cluster2-worker          <none>           <none>
submariner-lighthouse-coredns-749b7cf9c4-gzp68   1/1     Running   0          7d1h   10.129.1.7   cluster2-worker          <none>           <none>
submariner-metrics-proxy-qsnll                   2/2     Running   0          7d1h   10.129.1.4   cluster2-worker          <none>           <none>
submariner-operator-56ccb54ccf-fg6bs             1/1     Running   0          7d1h   10.129.1.3   cluster2-worker          <none>           <none>
submariner-routeagent-kxf76                      1/1     Running   0          7d1h   172.23.0.5   cluster2-control-plane   <none>           <none>
submariner-routeagent-ztzsf                      1/1     Running   0          7d1h   172.23.0.6   cluster2-worker          <none>           <none>

[3]
$ kubectl exec -it  -n submariner-operator  submariner-routeagent-kxf76 /bin/sh

**Comment by surfinlemex** [comment]
You can see that we have all those rules already. Unfortunately same result:
![image](https://user-images.githubusercontent.com/31878095/235409195-5b54c001-6ad5-4689-8d60-fb4e5240948a.png)


IPTABLES on both cluster GW node and non gw node wiht pod
![image](https://user-images.githubusercontent.com/31878095/235408983-647ccafe-94d4-4684-89af-0e16867840eb.png)
![image](https://user-images.githubusercontent.com/31878095/235409112-e98e1315-4b5f-4cb5-a95c-da76b6699ce4.png)

**Comment by yboaron** [comment]
Thanks @surfinlemex .

Trying to summarize the case : 

What's the problem?
  - inter cluster ICMP (ping) is fine while TCP connectivity test there is a delay of ~25 seconds  
  - Subctl verify e2e tests pass successfully

What did you try so far?

- Setting MSS_CLAMPING value (submariner.io/tcp-clamp-mss )  - didn't help
- Disable connection tracking (using iptables  NOTRACK) for Submariner traffic - didn't help


cc @sridhargaddam

**Comment by surfinlemex** [comment]
@yboaron  nothing was help... TCP-MSS 1000 or NOTRACK for iptables...

I have only one option... this issue related to CNI=OpenShift SDN = OVS. If you check captured traffic you can see intercluster traffic packets on external NIC.

**Comment by sridhargaddam** [comment]
@surfinlemex I strongly suspect this is some platform configuration issue. 

Lets try to narrow down the problem.
Please run the following command on the following Baremetal nodes.
1. The `Gateway` node of **BOTH** the clusters
2. The `node` on which the nginx server pod is scheduled.
3. The `node` on which the client pod is scheduled from where the curl command is issued to the server.

Command:
```
ethtool --offload vx-submariner rx off tx off
```

After executing the above command, you can try the curl command once again and let us know the behavior.

**Comment by surfinlemex** [comment]
@sridhargaddam Looks like the change you suggested resolve the issue
See screenshot blow:
![image](https://user-images.githubusercontent.com/31878095/235850355-20609e7c-157d-451c-86d8-ebb7cfc1b871.png)

**Comment by sridhargaddam** [comment]
@surfinlemex that's great to hear!! 

Can you let us know the following details from the BareMetal platform
1. OS details
2. Linux kernel version
3. OpenShift version
4. Iptables version.

**Comment by surfinlemex** [comment]
**1. OS details:**
cat system-release
Red Hat Enterprise Linux CoreOS release 4.10

**2. Linux kernel:**
Linux ams-oce2-ocp-is01 4.18.0-305.3.1.el8.x86_64 #1 SMP Tue Jun 1 16:14:33 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**3. OpenShift version:**
 oc version
Client Version: 4.10.0-202209291217.p0.g442535c.assembly.stream-442535c

**4.Iptables version:**
iptables --version
iptables v1.8.4 (nf_tables)


![image](https://user-images.githubusercontent.com/31878095/235888223-7c6f01c0-fab2-48a7-995c-4f6e5b53a6a0.png)

**Comment by surfinlemex** [comment]
@yboaron Can you please provide RCA of the issue we have?
Looks like command: **ethtool --offload vx-submariner rx off tx off** just workaround.

**Comment by yboaron** [comment]
Well, I can see multiple UDP packets with bad checksum captured in the pcap files you attached [1],

I assume that the root cause is some infrastructure issue (kernel or NIC firmware) causing bad checksum calculation for UDP packets as multiple similar issues have also been reported in other projects[2].


[1]
![image](https://github.com/submariner-io/submariner/assets/29688326/e5185568-9f01-43e9-9807-f1081654dbb9)

[2]
https://github.com/kubernetes-sigs/kubespray/issues/8992
https://github.com/projectcalico/calico/issues/3145

**Comment by dfarrell07** [comment]
I think @yboaron said he hopes to take a look at this when he has cycles
