### ISSUE TITLE
AWS: All submariner-routeagent pods got into CrashLoopBackOff

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/submariner#736]
**What happened**:

Right after a new submariner deploy and join, I see:

```
pod/submariner-routeagent-8554g                      0/1     CrashLoopBackOff   1          25s   app=submariner-routeagent,component=routeagent,controller-revision-hash=c677d9594,pod-template-generation=1
pod/submariner-routeagent-c7494                      0/1     CrashLoopBackOff   1          25s   app=submariner-routeagent,component=routeagent,controller-revision-hash=c677d9594,pod-template-generation=1
pod/submariner-routeagent-fmg5c                      0/1     CrashLoopBackOff   1          25s   app=submariner-routeagent,component=routeagent,controller-revision-hash=c677d9594,pod-template-generation=1
pod/submariner-routeagent-mf2f5                      0/1     CrashLoopBackOff   1          25s   app=submariner-routeagent,component=routeagent,controller-revision-hash=c677d9594,pod-template-generation=1
```

In routeagent pods logs I see:

```
Command:
      submariner-route-agent.sh
    State:          Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Wed, 22 Jul 2020 10:54:12 +0300
      Finished:     Wed, 22 Jul 2020 10:54:12 +0300

F0722 07:54:09.225159       1 main.go:97] Error running route controller: error annotating the node "ip-10-166-56-196" with cniIfaceIP: error updatating node "ip-10-166-56-196", err: unable to get node info for node ip-10-166-56-196, err: nodes "ip-10-166-56-196" not found
```

This issue is reproduced, so it's a blocker.

Please see full test report, including pod logs collection (last step):

- https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/debug_job/103/Test-Report/
- https://qe-jenkins-csb-skynet.cloud.paas.psi.redhat.com/job/Submariner-OSP-AWS/760/Test-Report/

**Environment**:
- subctl version: v0.5.0-6-gad8f10a

- Cluster A (AWS public):
Client Version: 4.5.2
Server Version: 4.5.2
Kubernetes Version: v1.18.3+b74c5ed

- Cluster B (OSP on-prem):
Client Version: 4.5.2
Server Version: 4.4.3
Kubernetes Version: v1.17.1

**Comment by manosnoam** [comment]
According to @sridhargaddam this bug is related to recent change:
 https://github.com/submariner-io/submariner/pull/729

Its something to do with hostnames. Which are constructed in a different manner on **AWS** only (it does not occur on OSP).
Basically its a new issue and looks like we did not validate hostNetworking to remoteService use-case where the sourcePod was on AWS Cluster.

**Comment by sridhargaddam** [comment]
On AWS Clusters, it was seen that nodes are named with FQDN (i.e., hostname.domainname). However, on many of the other
K8s clusters we tested so far (like KIND, OSP etc), the hostnames were matching with the nodeNames. 

In order to support connectivity from HostNetwork to remoteClusters (when using Globalnet), routeagent Pod annotates the respective nodes with the cniIfaceIP annotation. In the current code, where this annotation is added, we were using the hostname to query the node info. This was failing on AWS Clusters for the issue mentioned above.

This is now fixed via the following PR: https://github.com/submariner-io/submariner/pull/737

**Comment by manosnoam** [comment]
Thanks @sridhargaddam I've verified the fix

**Comment by linanh** [comment]
If nodes are named with FQDN (hostname.domainname), and pod node name use only part of FQDN(hostname). Then the issue still exists.

**Comment by manosnoam** [comment]
@linanh Can you share more info please, perhaps the failed pod logs ?

**Comment by sridhargaddam** [comment]
> If nodes are named with FQDN (hostname.domainname), and pod node name use only part of FQDN(hostname). Then the issue still exists.

The following PRs address this issue in Submariner:
https://github.com/submariner-io/submariner/pull/737
https://github.com/submariner-io/submariner/pull/738

Please check if you are using the Submariner image which includes these fixes. Also, if you can share the logs for submariner-route-agent pod, we can look into it.

**Comment by linanh** [comment]
1. OS hostname is named "node-01.example.com"
2. The node name is named "node-01" using rancher
3. error log: 
   Hostname is "node-01.example.com" and routeAgentNodeName is ""
   Error running route controller: could not get the nodeName on host "node-01.example.com"
5. Environment:
  submariner v0.6.0
  rancher rke (kubernetes v1.18.6)

**Comment by linanh** [comment]
@sridhargaddam , the command output is "node-01"

**Comment by sridhargaddam** [comment]
> @sridhargaddam , the command output is "node-01"

Thanks for the details @linanh 
I think this needs to be handled. Will push a PR shortly to fix it.

**Comment by sridhargaddam** [comment]
> > @sridhargaddam , the command output is "node-01"
> 
> Thanks for the details @linanh
> I think this needs to be handled. Will push a PR shortly to fix it.

@linanh Thanks for reporting the issue. The following PR will fix it: https://github.com/submariner-io/submariner/pull/783

**Comment by sridhargaddam** [comment]
@linanh the necessary fix is now merged, so closing the issue. Please let us know if you still see the issue.

**Comment by linanh** [comment]
Thanks, @sridhargaddam. By using submariner devel image, the submariner-route-agent is normal.

**Comment by mangelajo** [comment]
@Oats87  ^ :-)
